version: "3.9"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"  # Expose Nuxt internally to Docker network (no need to map it to host)
    environment:
      - HOST=0.0.0.0
    command: npm run start

  nginx:
    image: nginx
    ports:
      - "80:80"  # Expose port 80 to the outside world
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx config
      - ./dist:/usr/share/nginx/html  # Mount dist folder to serve _nuxt and static files
    depends_on:
      - nuxt

