version: "3.9"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - HOST=0.0.0.0
    command: npm run start

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - nuxt