version: "3.9"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"  # Expose Nuxt internally to Docker network (no need to map it to host)
    environment:
      - HOST=0.0.0.0
    command: npm run start

  nginx:
    image: nginx
    ports:
      - "80:80"  # Map port 80 of host to port 80 in Nginx container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Map custom Nginx config
      - ./static:/usr/share/nginx/html/static  # Map static folder
    depends_on:
      - nuxt
