version: "3.9"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose Nuxt.js directly on port 3000 for testing
    environment:
      - HOST=0.0.0.0
    command: npm run start
